# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, '\uc77c\uc694\uc77c'), (1, '\uc6d4\uc694\uc77c'), (2, '\ud654\uc694\uc77c'), (3, '\uc218\uc694\uc77c'), (4, '\ubaa9\uc694\uc77c'), (5, '\uae08\uc694\uc77c'), (6, '\ud1a0\uc694\uc77c')], default=0)),
                ('start_time', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(86399), django.core.validators.MinValueValidator(0)])),
                ('end_time', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(86399), django.core.validators.MinValueValidator(0)])),
                ('place', models.CharField(max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Member')),
            ],
        ),
    ]
